[build]
  command = 'nuxt generate'
  functions = 'netlify/functions'
  publish = 'dist'

[[redirects]]
  from = '/*'
  to = '/index.html'
  status = 200

[dev]
  command = 'npm run start'
  port = 3000
  publish = 'dist'